Реализован калькулятор на Vue
js-tasks-ru/vue-20220616_evlushin-anton-viktorovich pull request #2
Opened 2022-06-25 22:35 UTC by Evlushin

2022-06-26 08:48 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-06-26 13:23 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-06-28 16:53 UTC, ShGKme requested changes
В  `01-basics/02-VueCalculator/` требуется явно реализовать вычисляемое свойство.

Для закрепления работы с `computed` предлагаю в `03-MarkedList` тоже  реализовать через computed.

2022-06-28 16:53 UTC, ShGKme commented on 01-basics/02-VueCalculator/script.js
> +  },
Здесь через три отслеживания реализовано классическое вычисляемое свойство в `z`. Свойство `z` не имеет собственного значения, в нём всегда лежит результат вычисления через `calc`, который вычисляет значение на основе других реактивных данных. При этом потребовалось самостоятельно думать о том, от каких данных зависит это вычисление, чтобы добавить все необходимые отслеживания.

Описание вычисляемого свойства в `computed` позволит явно описать свойство, как "вычисляемое", чтобы его значение могло только вычисляться самим Vue, при этом вычислялось само, лениво, и самостоятельно определяло зависимости вычисления.

2022-06-28 16:53 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +    </ul>
Значением `class` при привязке может быть и массив, и объект, и просто строка. Оборачивать одно значение в массив не обязательно, это тоже самое, что `:class="email.class"`

2022-06-28 16:53 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +      })(),
Какую роль здесь играет IIFE для вычисления emails?

2022-06-28 16:53 UTC, ShGKme commented on 01-basics/04-MeetupTitle/script.js
> +      addTitle();
Аналогично - не совсем понимаю, зачем нужна функция addTitle, как отдельная функция?

2022-06-28 16:53 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +    },
Это отслеживание также реализует вычисляемое свойство, но прямо в `emails`. Такое решение работает, пока при вычислении не теряются оригинальные данные, и только добавляется дополнительный `class`. За этим нужно следить. Подобное решение могло быть для оптимизаций, если вместо `map` с пересозданием массива и объектов бы только мутировались поля `class`, но такая оптимизация актуальна, если данных много.

Лучше реализовать отдельно вычисляемое свойство, которое вернёт результат этого `map`, не затирая исходный массив митапов.

2022-06-29 08:47 UTC, Evlushin commented on 01-basics/03-MarkedList/index.html
> +    </ul>
Буду иметь ввиду, спасибо, переделаю

2022-06-29 08:47 UTC, Evlushin commented on 01-basics/02-VueCalculator/script.js
> +  },
переделаю на computed

2022-06-29 08:48 UTC, Evlushin commented on 01-basics/03-MarkedList/script.js
> +      })(),
Для того чтобы получить результат функции а не саму функцию

2022-06-29 09:07 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +      })(),
Можно прямо использовать значение, не вычисляя его в отдельной функции

```javascript
emails: emails.map(function (email) {
  return {
    name: email,
    class: '',
  };
}),
```

или со стрелочной функцией

```javascript
emails: emails.map((email) => ({
  name: email,
  class: '',
}),
```

2022-07-11 07:29 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2022-07-11 08:11 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-11 09:03 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-11 09:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @ShGKme

2022-07-11 13:12 UTC, ShGKme approved these changes
Все задачи приняты 👍

2022-07-11 13:12 UTC, ShGKme commented on 01-basics/03-MarkedList/index.html
> +        </ul>
Если класс один, его можно не оборачивать в массив, передавая просто строку.

2022-07-11 13:12 UTC, ShGKme commented on 01-basics/03-MarkedList/script.js
> +  },
Лучше в `map` передавать стрелочную функцию, а не `function`. Так там будет доступен экземпляр компонента через `this`.

2022-07-11 13:12 UTC, merged